name = "ingest-website"
compatibility_date = "2025-12-02"

[env.production]
routes = [
  { pattern = "ingest.mov", zone_name = "ingest.mov" },
  { pattern = "www.ingest.mov", zone_name = "ingest.mov" }
]

[site]
bucket = "."
